### PR TITLE
Navigation testing

### PR DESCRIPTION
**Pull request by JHannTX**
One test doesn't work, but it shouldn't as there is currently no function to show a users account.

### CODE REVIEW

**Review by dfields16 — COMMENTED** [review]
Does this nav work with the changes to the Admin Page? Admin Page uses buttons and not links.

**Review by ColbyMainard — COMMENTED** [review]
I ran the tests locally, there was one error in
    Scenario: I cannot view a user without being an admin
but everything else looks like it functions as expected.  I think it has something to do with Dawson's latest push to develop branch where he switched some links for buttons.  
Everything else seems to be in order though!

**Comment by JHannTX** [comment]
@ColbyMainard I said when I opened the pull request one test doesn't work and that is expected.  It has to do with that functionality isn't even implemented.

@dfields16 I don't know.  Let me merge with develope and fix anything that needs fixing.

**Review by ColbyMainard — APPROVED** [review]

**Review by dfields16 — APPROVED** [review]
Double Check the testing works after I merge it.

**Pull request merged**
